### ISSUE TITLE
Incorrect client stack value

### ISSUE THREAD

**Issue by crouchingtiger** [valga/fbns-react#1]
https://github.com/valga/fbns-react/blob/d370bdfe768c21271a76d8b3fff1b3c2c08804ef/src/Connection.php#L89

Just did a slight review here while trying to debug an issue with my own library, should this not be:

``$this->clientStack = self::FBNS_CLIENT_STACK;``

It doesn't seem to have any negative effect right now in any case.

**Comment by crouchingtiger** [comment]
I'm also sending field ID's 22-25 in my library (based off the protocol definition from 10.32.0). Doesn't seem to make much of a difference, but might cause issues down the road in terms of detection if they're not present.

22 = FBNS connection key (long)
23 = FBNS connection secret (string)
24 = FBNS device ID (string)
25 = FBNS device secret (string)

Sorry that I don't have time to make a proper PR right now.

**Comment by valga** [comment]
@crouchingtiger Hmm, 10.29.0 has these fields in protocol definition, but it doesn't send them. I have no time to check recent versions at the moment.

By the way, what values are being sent by 10.32.0? Same as in username/password or just empty?

**Comment by valga** [comment]
@crouchingtiger Here is a captured `CONNECT` thrift from 13.0.0.1.91:
```
1 (08): "deadbeef-dead-beef-0"
4/1 (06): 0
4/2 (08): "[FBAN/MQTT;FBAV/13.0.0.1.91;FBBV/69989691;FBDM/{density=3.0,width=1080,height=1920};FBLC/en_US;FBCR/Carrier;FBMF/Manufacturer;FBBD/Brand;FBPN/com.instagram.android;FBDV/Model;FBSV/7.0;FBBK/1;FBCA/armeabi-v7a:armeabi;]"
4/3 (06): 439
4/4 (06): 128
4/5 (05): 1
4/6 (01): true
4/7 (02): false
4/8 (08): ""
4/9 (02): false
4/10 (05): 1
4/11 (05): 0
4/12 (06): 1234567890
4/14 (05): [76, 80]
4/15 (08): "device_auth"
4/16 (06): 567310203415052
4/20 (08): ""
4/21 (03): 3
5 (08): ""
```

No need to send fields 22-25, at least for Instagram app. Although other apps may use them to use single network connection for multiple endpoints.

**Comment by crouchingtiger** [comment]
Looks good then. I've actually not yet tried to capture the MQTT packets so far and was going still off decompilation. 

Are you using this [thrift plugin](https://github.com/andrewcox/wireshark-with-thrift-plugin) to read these in Wireshark?

**Comment by valga** [comment]
Actually I don't want to tell anyone how I am capturing the packets, because I am doing it in the most embarrassing way. I am too lazy to use Wireshark.
