### ISSUE TITLE
Update composer requirements

### ISSUE THREAD

**Issue by mgp25** [valga/fbns-react#4]
Hello @valga !

In the latest version of Instagram API we use:

```php
use BinSoul\Net\Mqtt\DefaultPacketFactory;
```

Since we are using an outdated version we are getting:

```
Fatal error: Uncaught Error: Class 'BinSoul\Net\Mqtt\DefaultPacketFactory' not found in /Users/MarkZuckerberg/Documents/GitHub/Instagram/src/Realtime/Mqttot/ReactMqttClient.php:124
Stack trace:
#0 /Users/MarkZuckerberg/Documents/GitHub/Instagram/src/Realtime/Mqtt.php(573): InstagramAPI\Realtime\Mqttot\ReactMqttClient->__construct(Object(InstagramAPI\React\Connector), Object(React\EventLoop\ExtEventLoop), NULL, Object(InstagramAPI\Realtime\Mqtt\StreamParser))
#1 /Users/MarkZuckerberg/Documents/GitHub/Instagram/src/Realtime/Mqtt.php(130): InstagramAPI\Realtime\Mqtt->_getClient()
#2 /Users/MarkZuckerberg/Documents/GitHub/Instagram/src/Realtime.php(119): InstagramAPI\Realtime\Mqtt->__construct(Object(InstagramAPI\Realtime), Object(InstagramAPI\React\Connector), Object(InstagramAPI\Realtime\Mqtt\Auth), Object(InstagramAPI\Devices\Device), Object(InstagramAPI\Instagram), Object(React\EventLoop\ExtEventLoop), Object(Monolog\Logger), Array)
#3 /Users/MarkZuckerberg/Documents/GitHub/Instagram/src/Realtime.php(80): InstagramAPI\Realtime->_buildMqttClient()
#4 /Users/MarkZuckerberg/Doc in /Users/MarkZuckerberg/Documents/GitHub/Instagram/src/Realtime/Mqttot/ReactMqttClient.php on line 124
```

`DefaultPacketFactory` is only available in:

`"binsoul/net-mqtt-client-react": "^0.6.0",` and upwards. Because of this change, it is also required:

`"react/socket": "^1.3",`

So it would be great if you could update composer to avoid:

```
  Problem 1
    - valga/fbns-react 0.1.9 requires react/socket ~0.8 -> satisfiable by react/socket[v0.8.1, v0.8.8, v0.8.2, v0.8.6, v0.8.9, v0.8.4, v0.8.0, v0.8.5, v0.8.11, v0.8.12, v0.8.3, v0.8.10, v0.8.7] but these conflict with your requirements or minimum-stability.
    - valga/fbns-react 0.1.9 requires react/socket ~0.8 -> satisfiable by react/socket[v0.8.1, v0.8.8, v0.8.2, v0.8.6, v0.8.9, v0.8.4, v0.8.0, v0.8.5, v0.8.11, v0.8.12, v0.8.3, v0.8.10, v0.8.7] but these conflict with your requirements or minimum-stability.
    - valga/fbns-react 0.1.9 requires react/socket ~0.8 -> satisfiable by react/socket[v0.8.1, v0.8.8, v0.8.2, v0.8.6, v0.8.9, v0.8.4, v0.8.0, v0.8.5, v0.8.11, v0.8.12, v0.8.3, v0.8.10, v0.8.7] but these conflict with your requirements or minimum-stability.
    - Installation request for valga/fbns-react ^0.1.9 -> satisfiable by valga/fbns-react[0.1.9].
```

Also your packagist isn't automatically updated, probably the hook was outdated, I requested an update through packagist so now it has `0.1.9`.

Best regards!

**Comment by valga** [comment]
@mgp25 Hi, see 67d9a15f41c56caa8219a630f01e2c7ac43ed778. I updated net-mqtt to the latest version, but there is a problem that prevents us from using custom packet factories in PHP <7.4.

I temporarily locked PHP version to 7.4 and filed a PR.

By the way, I checked your recent Realtime update and I think that we can reduce the amount of duplicated code (extended Thrift, connection stuff, etc) between our repos. What do you think about that?

**Comment by mgp25** [comment]
@valga I will send you later today the MQTToT CONNECT packets for both Realtime and FBNS. By the way, can you push a new release for https://github.com/valga/fbns-react/commit/67d9a15f41c56caa8219a630f01e2c7ac43ed778 ?

Best regards

**Comment by valga** [comment]
@mgp25 I will wait about a week for binsoul to approve the PRs. In case he won't I will either release it as is or include a patched client to support PHP 7.2+ just like you did. Also I want to push a couple of improvements.

In the meantime you can use `dev-master` as version constraint.

**Comment by valga** [comment]
@mgp25 Hey, I [included](https://github.com/valga/fbns-react/commit/cec67fc1bbb9b06b5fda5ea32061d15a9b13cc67) patched MQTT client into the library, so you can change PHP version constraint back to `^7.2`.

**Comment by mgp25** [comment]
@valga done! I will update parsers later tonight
